CREATE DATABASE burger_db;
USE burger_db;

CREATE TABLE burgers (
id INTEGER (30) AUTO IMCREMENT NOT NULL,
burger_name VARCHAR (20) NOT NULL,
devoured BOOLEAN DEFAULT FALSE,
date TIMESTAMP,
PRIMARY KEY (id)
);